# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "HemingPress"
license = "MIT"
licenselink = "https://github.com/arranf/hemingpress/blob/master/LICENSE.md"
description = "A Hemingway/VuePress inspired blog theme for hugo"
homepage = "https://github.com/arranf/hemingpress"
tags = ["blog", "VuePress", "Vue"]
features = ["html5", "css3"]
min_version = 0.30

[author]
  name = "Arran France"
  homepage = "https://arranfrance.com"
